// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjz3wX3QyvC7I408nebaRb-_jk-J30a0s',
    appId: '1:524432194075:web:187b4d3133485f66cd16be',
    messagingSenderId: '524432194075',
    projectId: 'signspeak-33e4a',
    authDomain: 'signspeak-33e4a.firebaseapp.com',
    storageBucket: 'signspeak-33e4a.firebasestorage.app',
    measurementId: 'G-K44JKL6761',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSKPrz60mZbyjlAXNOAx9Ax2EB2XgMz7Y',
    appId: '1:524432194075:android:df914c3a2bbe2a32cd16be',
    messagingSenderId: '524432194075',
    projectId: 'signspeak-33e4a',
    storageBucket: 'signspeak-33e4a.firebasestorage.app',
  );
}
