import 'package:flutter/material.dart';

class Localization {
  static String currentLanguage = 'en';
  static String userName = 'Guest User';
  static String userEmail = 'guest@signspeak.online';
  static bool bypassStream = false;

  static final ValueNotifier<String> appLanguageNotifier = ValueNotifier('en');

  static void changeLanguage(String langCode) {
    currentLanguage = langCode;
    appLanguageNotifier.value = langCode;
  }

  static final Map<String, Map<String, String>> _strings = {
    'en': {
      'login': 'Login',
      'signup': 'Sign Up',
      'welcome_back': 'Welcome Back 👋',
      'login_subtitle': 'Login to continue your journey',
      'create_account': 'Create Account ✨',
      'email': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'full_name': 'Full Name',
      'no_account': 'Don’t have an account? ',
      'have_account': 'Already have an account? ',
      'brand_name': 'SignSpeak',
      'guest': 'Guest User',
      'nav_home': 'Home',
      'nav_tutorials': 'Tutorials',
      'nav_signcam': 'SignCam',
      'nav_contact': 'Profile',
      'hero_title': 'Real-Time Sign Language Recognition',
      'hero_desc': 'Empowering seamless communication with cutting-edge AI that translates sign language into text and speech.',
      'hero_btn1': 'Launch SignCam',
      'hero_btn2': 'Start Learning Free',
      'features_title': 'Powerful Features',
      'feature_fast': 'Lightning-Fast Recognition',
      'feature_fast_desc': '98.2% accuracy with sub-second latency.',
      'feature_lang': 'Multi-Language Support',
      'feature_lang_desc': 'Expanding support for global deaf communities.',
      'feature_privacy': 'Privacy First',
      'feature_privacy_desc': 'On-device processing ensures your gestures never leave your device.',
      'tut_main_title': 'Learn Sign Language',
      'tut_alphabet': 'Alphabet & Numbers',
      'tut_alphabet_desc': 'Master fingerspelling and counting — the foundation of fluent signing.',
      'tut_everyday': 'Everyday Conversations',
      'tut_everyday_desc': 'Greetings, introductions, and common phrases for real-world use.',
      'tut_advanced': 'Advanced Grammar',
      'tut_advanced_desc': 'Non-manual markers, classifiers, and complex sentence structures.',
      'tut_btn1': 'Start Lesson',
      'tut_alpha_header': 'Master the Sign Language Alphabet',
      'tut_alpha_start': 'Start Learning Sign Language Alphabet And Numbers',
      'tut_video_alpha_single': 'Alphabets Tutorial (Single Hand)',
      'tut_video_alpha_double': 'Alphabets Tutorial (Double Hand)',
      'tut_video_num_basic': 'Numbers Tutorial (1-100)',
      'tut_video_num_large': 'Large Numbers Tutorial',
      'tut_everyday_header': 'Start Learning Everyday Conversations',
      'tut_video_basic': '30 Signs You Need to Know for Basic Conversations',
      'tut_video_first': 'Your First Conversations (99 Signs)',
      'tut_video_family': 'Family Conversations & Signs',
      'tut_gram_header': 'Advanced Sign Language Grammar',
      'tut_gram_1': 'Your First Grammar Lesson',
      'tut_gram_2': 'Sentence Structure Explained',
      'tut_gram_3': 'Directional Signs for Beginners',
      'cam_header': 'SignCam - AI Recognition',
      'cam_status': 'Camera Status: Ready',
      'cam_instruction': 'Please make sure your hand is visible in the frame.',
      'cam_output_label': 'Detected Sign:',
      'detected_word': 'Detected Word',
      'generated_sentence': 'Generated Sentence',
      'waiting': 'Waiting...',
      'sentences_placeholder': 'Sentences will appear here as you sign...',
      'speak_btn': '🔊 Speak',
      'clear_btn': '🗑 Clear',
      'profile_title': 'My Profile',
      'profile_joined': 'Member since: July 2026',
      'profile_lessons': 'Completed Lessons',
      'profile_streak': 'Learning Streak',
      'profile_settings': 'Account Settings',
      'logout_btn': 'Logout',
      'contact_web_btn': 'Contact Us on Website',
      'contact_web_desc': 'Need help or want to read our research? Open our website contact page.',
      'simulator_title': 'Gesture Simulator (For Testing)',
      'simulator_desc': 'Since gesture models run on-device, use this panel to simulate different signs and see the real-time phrase mapping and Text-To-Speech conversion.',
      'space_gesture': 'SPACE (Trigger Sentence Mapping)',
    },
    'ur': {
      'login': 'لاگ ان',
      'signup': 'سائن اپ',
      'welcome_back': 'خوش آمدید 👋',
      'login_subtitle': 'اپنا سفر جاری رکھنے کے لیے لاگ ان کریں',
      'create_account': 'نیا اکاؤنٹ بنائیں ✨',
      'email': 'ای میل ایڈریس',
      'password': 'پاس ورڈ',
      'confirm_password': 'پاس ورڈ کی تصدیق کریں',
      'forgot_password': 'پاس ورڈ بھول گئے؟',
      'full_name': 'پورا نام',
      'no_account': 'کیا اکاؤنٹ نہیں ہے؟ ',
      'have_account': 'پہلے سے اکاؤنٹ ہے؟ ',
      'brand_name': 'سائن اسپیک',
      'guest': 'مہمان صارف',
      'nav_home': 'ہوم',
      'nav_tutorials': 'ٹیوٹوریلز',
      'nav_signcam': 'سائن کیم',
      'nav_contact': 'پروفائل',
      'hero_title': 'اشاروں کی زبان کی پہچان',
      'hero_desc': 'جدید AI کے ذریعے اشاروں کو متن اور قدرتی آواز میں تبدیل کر کے رابطوں کو آسان بنائیں۔',
      'hero_btn1': 'سائن کیم شروع کریں',
      'hero_btn2': 'مفت سیکھنا شروع کریں',
      'features_title': 'طاقتور خصوصیات',
      'feature_fast': 'تیز ترین شناخت',
      'feature_fast_desc': '98.2% درستگی اور فوری نتائج۔',
      'feature_lang': 'کثیر لسانی سپورٹ',
      'feature_lang_desc': 'عالمی بہرے طبقے کے لیے سپورٹ۔',
      'feature_privacy': 'پرائیویسی پہلے',
      'feature_privacy_desc': 'آپ کا ڈیٹا آپ کے آلے تک محفوظ۔',
      'stats_title': 'ہمارا عالمی اثر',
      'stats_deaf': '70M+',
      'stats_deaf_text': 'دنیا بھر میں بہرے افراد',
      'stats_languages': '300+',
      'stats_languages_text': 'تعاون یافتہ اشاروں کی زبانیں',
      'stats_accuracy': '98.2%',
      'stats_accuracy_text': 'پہچاننے کی درستگی',
      'stats_users': '120K+',
      'stats_users_text': 'فعال صارفین',
      'tut_main_title': 'سائن لینگویج سیکھیں',
      'tut_alphabet': 'حروف تہجی اور اعداد',
      'tut_alphabet_desc': 'انگلیوں کے اشارے اور گنتی میں مہارت حاصل کریں۔',
      'tut_everyday': 'روزمرہ گفتگو',
      'tut_everyday_desc': 'سلام، تعارف، اور عام استعمال کے جملے۔',
      'tut_advanced': 'اعلیٰ گرامر',
      'tut_advanced_desc': 'پیچیدہ جملے کی ساخت اور گرامر سیکھیں۔',
      'tut_btn1': 'سبق شروع کریں',
      'tut_alpha_header': 'حروف تہجی کے اشارے سیکھیں',
      'tut_alpha_start': 'اشاروں کی زبان کے حروف تہجی اور اعداد سیکھنا شروع کریں',
      'tut_video_alpha_single': 'حروف تہجی ٹیوٹوریل (ایک ہاتھ سے)',
      'tut_video_alpha_double': 'حروف تہجی ٹیوٹوریل (دونوں ہاتھوں سے)',
      'tut_video_num_basic': 'گنتی کا ٹیوٹوریل (1 سے 100 تک)',
      'tut_video_num_large': 'بڑے اعداد سیکھنے کا ٹیوٹوریل',
      'tut_everyday_header': 'روزمرہ گفتگو کے اشارے سیکھیں',
      'tut_video_basic': 'بنیادی گفتگو کے لیے 30 ضروری اشارے',
      'tut_video_first': 'آپ کی پہلی گفتگو (99 اہم اشارے)',
      'tut_video_family': 'خاندان اور رشتوں کے لیے اشارے',
      'tut_gram_header': 'اعلیٰ سائن لینگویج گرامر',
      'tut_gram_1': 'پہلا گرامر سبق',
      'tut_gram_2': 'جملے کی ساخت کی مکمل وضاحت',
      'tut_gram_3': 'سمتی اشارے (نو آموز افراد کے لیے)',
      'cam_header': 'سائن کیم - AI شناخت',
      'cam_status': 'کیمرہ کی حالت: تیار',
      'cam_instruction': 'براہ کرم یقینی بنائیں کہ آپ کا ہاتھ فریم میں نظر آ رہا ہے۔',
      'cam_output_label': 'پہچانا گیا اشارہ:',
      'detected_word': 'شناخت شدہ لفظ',
      'generated_sentence': 'تخلیق شدہ جملہ',
      'waiting': 'انتظار کر رہا ہوں...',
      'sentences_placeholder': 'جیسے ہی آپ اشارہ کریں گے، جملے یہاں ظاہر ہوں گے...',
      'speak_btn': '🔊 بولیں',
      'clear_btn': '🗑 صاف کریں',
      'profile_title': 'میرا پروفائل',
      'profile_joined': 'رکنیت کی تاریخ: جولائی 2026',
      'profile_lessons': 'مکمل شدہ اسباق',
      'profile_streak': 'سیکھنے کا تسلسل',
      'profile_settings': 'اکاؤنٹ کی ترتیب',
      'logout_btn': 'لاگ آؤٹ',
      'contact_web_btn': 'ویب سائٹ پر ہم سے رابطہ کریں',
      'contact_web_desc': 'مدد کی ضرورت ہے یا ہماری تحقیق پڑھنا چاہتے ہیں؟ ہماری ویب سائٹ کا رابطہ صفحہ کھولیں۔',
      'simulator_title': 'اشارہ سیمولیٹر (ٹیسٹنگ کے لیے)',
      'simulator_desc': 'چونکہ اشارہ ماڈلز آن ڈیوائس چلتے ہیں، مختلف اشاروں کی نقل کرنے اور فوری جملہ سازی اور آواز دیکھنے کے لیے اس پینل کا استعمال کریں۔',
      'space_gesture': 'اسپیس (جملے کی ساخت بنائیں)',
    },
    'sd': {
      'login': 'لاگ ان',
      'signup': 'سائن اپ',
      'welcome_back': 'ڀليڪار 👋',
      'login_subtitle': 'پنهنجو سفر جاري رکڻ لاءِ لاگ ان ڪريو',
      'create_account': 'نئون اڪائونٽ ٺاهيو ✨',
      'email': 'اي ميل پتو',
      'password': 'پاسورڊ',
      'confirm_password': 'پاسورڊ جي تصديق ڪريو',
      'forgot_password': 'پاسورڊ وسري ويو؟',
      'full_name': 'پورو نالو',
      'no_account': 'ڇا اڪائونٽ ناهي؟ ',
      'have_account': 'پهرين کان اڪائونٽ آهي؟ ',
      'brand_name': 'سائن اسپیڪ',
      'guest': 'مهمان واپرائيندڙ',
      'nav_home': 'هوم',
      'nav_tutorials': 'ٽيوٽوريلز',
      'nav_signcam': 'سائن ڪيم',
      'nav_contact': 'پروفائيل',
      'hero_title': 'اشارن جي ٻوليءَ جي سڃاڻپ',
      'hero_desc': 'جديد AI ذريعي اشارن جي ٻوليءَ کي متن ۽ آواز ۾ ترجمو ڪري رابطن کي آسان بڻايو.',
      'hero_btn1': 'سائن ڪيم لانچ ڪريو',
      'hero_btn2': 'مفت سکڻ شروع ڪريو',
      'features_title': 'طاقتور خاصيتون',
      'feature_fast': 'تيز ترين سڃاڻپ',
      'feature_fast_desc': '98.2% درستگي ۽ فوري نتيجا.',
      'feature_lang': 'ڪثير لساني سپورٽ',
      'feature_lang_desc': 'عالمي ٻوڙن جي طبقن لاءِ مدد.',
      'feature_privacy': 'پرائيويسي پهرين',
      'feature_privacy_desc': 'توهان جو ڊيٽا توهان جي ڊوائيس تائين محفوظ آهي.',
      'tut_main_title': 'سائن ٻولي سکو',
      'tut_alphabet': 'اکر ۽ انگ',
      'tut_alphabet_desc': 'آڱرين جا اشارا ۽ ڳڻپ سکو — رواني سان ڳالهائڻ جو بنياد.',
      'tut_everyday': 'روزاني گفتگو',
      'tut_everyday_desc': 'سلام، تعارف، ۽ عام استعمال جا جملا.',
      'tut_advanced': 'اعليٰ گرامر',
      'tut_advanced_desc': 'پيچيده جملن جي بناوت ۽ گرامر سکو.',
      'tut_btn1': 'سبق شروع ڪريو',
      'tut_alpha_header': 'اکرن جا اشارا سکو',
      'tut_alpha_start': 'اشارن جي ٻولي جا اکر ۽ انگ سکڻ شروع ڪريو',
      'tut_video_alpha_single': 'اکرن جو ٽيوٽوريل (هڪ هٿ)',
      'tut_video_alpha_double': 'اکرن جو ٽيوٽوريل (ٻه هٿ)',
      'tut_video_num_basic': 'ڳڻپ جو ٽيوٽوريل (1-100)',
      'tut_video_num_large': 'وڏن انگن جو ٽيوٽوريل',
      'tut_everyday_header': 'روزاني گفتگو جا اشارا',
      'tut_video_basic': '30 ضروري اشارا جيڪي توهان کي معلوم هئڻ گهرجن',
      'tut_video_first': 'توهان جي پهرين گفتگو (99 اشارا)',
      'tut_video_family': 'خانداني گفتگو ۽ اشارا',
      'tut_gram_header': 'اعليٰ sائن ٻولي گرامر',
      'tut_gram_1': 'پهريون گرامر سبق',
      'tut_gram_2': 'جملي جي بناوت جي وضاحت',
      'tut_gram_3': 'سمتي اشارا (شروعات ڪندڙن لاءِ)',
      'cam_header': 'سائن ڪيم - AI سڃاڻپ',
      'cam_status': 'ڪيمرا جي حالت: تيار',
      'cam_instruction': 'مهرباني ڪري پڪ ڪريو ته توهان جو هٿ فريم ۾ نظر اچي رهيو آهي.',
      'cam_output_label': 'سڃاڻپ ٿيل اشارو:',
      'detected_word': 'سڃاتل لفظ',
      'generated_sentence': 'ٺهيل جملو',
      'waiting': 'انتظار ڪري رهيو آهيان...',
      'sentences_placeholder': 'جملا هتي ظاهر ٿيندا جڏهن توهان اشارو ڪندا...',
      'speak_btn': '🔊 ڳالهايو',
      'clear_btn': '🗑 صاف ڪريو',
      'profile_title': 'منهنجي پروفائيل',
      'profile_joined': 'ميمبرشپ جي تاريخ: جولاءِ 2026',
      'profile_lessons': 'مکمل ٿيل سبق',
      'profile_streak': 'سکڻ جو سلسلو',
      'profile_settings': 'اڪائونٽ سيٽنگون',
      'logout_btn': 'لاگ آئوٽ',
      'contact_web_btn': 'ويب سائيٽ تي اسان سان رابطو ڪريو',
      'contact_web_desc': 'مدد گهرجي يا اسان جي تحقيق پڙهڻ چاهيو ٿا؟ اسان جي ويب سائيٽ جو رابطو صفحو کوليو.',
      'simulator_title': 'اشارو سموليٽر (ٽيسٽنگ لاءِ)',
      'simulator_desc': 'جيئن ته ashara ماڊل آن ڊوائيس هلن ٿا، مختلف اشارن جي نقل ڪرڻ ۽ آواز ڏسڻ لاءِ هن پينل کي استعمال ڪريو.',
      'space_gesture': 'اسپيس (جملو مڪمل ڪريو)',
    },
    'ar': {
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'welcome_back': 'مرحباً بعودتك 👋',
      'login_subtitle': 'قم بتسجيل الدخول لمواصلة رحلتك',
      'create_account': 'إنشاء حساب جديد ✨',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'full_name': 'الاسم الكامل',
      'no_account': 'ليس لديك حساب؟ ',
      'have_account': 'لديك حساب بالفعل؟ ',
      'brand_name': 'ساين سبيك',
      'guest': 'مستخدم زائر',
      'nav_home': 'الرئيسية',
      'nav_tutorials': 'الدروس',
      'nav_signcam': 'ساين كام',
      'nav_contact': 'ملفي الشخصي',
      'hero_title': 'التعرف على لغة الإشارة فوراً',
      'hero_desc': 'تمكين التواصل السلس باستخدام الذكاء الاصطناعي الذي يترجم لغة الإشارة إلى نص وصوت طبيعي.',
      'hero_btn1': 'ابدأ ساين كام',
      'hero_btn2': 'ابدأ التعلم مجاناً',
      'features_title': 'ميزات قوية',
      'feature_fast': 'تعرف فائق السرعة',
      'feature_fast_desc': 'دقة 98.2٪ مع زمن استجابة سريع.',
      'feature_lang': 'دعم لغات متعددة',
      'feature_lang_desc': 'توسيع الدعم لمجتمعات الصم العالمية.',
      'feature_privacy': 'الخصوصية أولاً',
      'feature_privacy_desc': 'المعالجة على الجهاز تضمن بقاء بياناتك آمنة.',
      'tut_main_title': 'تعلم لغة الإشارة',
      'tut_alphabet': 'الأبجدية والأرقام',
      'tut_alphabet_desc': 'أتقن هجاء الأصابع والعد — أساس التحدث بطلاقة.',
      'tut_everyday': 'المحادثات اليومية',
      'tut_everyday_desc': 'التحيات، التعارف، والعبارات الشائعة.',
      'tut_advanced': 'قواعد متقدمة',
      'tut_advanced_desc': 'تعلم تراكيب الجمل المعقدة والقواعد.',
      'tut_btn1': 'ابدأ الدرس',
      'tut_alpha_header': 'أتقن أبجدية لغة الإشارة',
      'tut_alpha_start': 'ابدأ بتعلم أبجدية وأرقام لغة الإشارة',
      'tut_video_alpha_single': 'دروس الأبجدية (يد واحدة)',
      'tut_video_alpha_double': 'دروس الأبجدية (يدين)',
      'tut_video_num_basic': 'دروس الأرقام (1-100)',
      'tut_video_num_large': 'دروس الأرقام الكبيرة',
      'tut_everyday_header': 'ابدأ تعلم المحادثات اليومية',
      'tut_video_basic': '30 إشارة يجب أن تعرفها للمحادثات الأساسية',
      'tut_video_first': 'محادثاتك الأولى (99 إشارة)',
      'tut_video_family': 'محادثات الأسرة والإشارات',
      'tut_gram_header': 'قواعد لغة الإشارة المتقدمة',
      'tut_gram_1': 'درس القواعد الأول',
      'tut_gram_2': 'شرح تركيب الجملة',
      'tut_gram_3': 'علامات الاتجاه للمبتدئين',
      'cam_header': 'ساين كام - التعرف بالذكاء الاصطناعي',
      'cam_status': 'حالة الكاميرا: جاهزة',
      'cam_instruction': 'يرجى التأكد من أن يدك مرئية في الإطار.',
      'cam_output_label': 'الإشارة المكتشفة:',
      'detected_word': 'الكلمة المكتشفة',
      'generated_sentence': 'الجملة الناتجة',
      'waiting': 'في الانتظار...',
      'sentences_placeholder': 'ستظهر الجمل هنا عندما تبدأ بالإشارة...',
      'speak_btn': '🔊 تحدث',
      'clear_btn': '🗑 مسح',
      'profile_title': 'ملفي الشخصي',
      'profile_joined': 'عضو منذ: يوليو 2026',
      'profile_lessons': 'الدروس المكتملة',
      'profile_streak': 'نشاط التعلم متواصل',
      'profile_settings': 'إعدادات الحساب',
      'logout_btn': 'تسجيل الخروج',
      'contact_web_btn': 'اتصل بدعم الموقع',
      'contact_web_desc': 'هل تحتاج إلى مساعدة أو تريد قراءة أبحاثنا؟ افتح صفحة الاتصال الخاصة بنا على الموقع.',
      'simulator_title': 'محاكي الإشارات (للاختبار)',
      'simulator_desc': 'بما أن نماذج الإشارات تعمل على الجهاز، استخدم هذه اللوحة لمحاكاة إشارات مختلفة ورؤية تركيب الجمل الفوري والصوت.',
      'space_gesture': 'مسافة (تفعيل تركيب الجملة)',
    }
  };

  // --- Sign Maps (Phrase Mapping in signcam) ---
  static final Map<String, Map<String, String>> multiLangMap = {
    'en': {
      'HELP': 'I need help! Please assist me.',
      'HELLO': 'Hello! Greetings to you.',
      'WATER': 'I am thirsty, I need water.',
      'FOOD': 'I am hungry. Give me food.',
      'DANGER': 'Danger! Be careful and stay safe.',
      'WASHROOM': 'Where is the washroom?',
      'GOOD': 'Good & Excellent! Great job.',
      'EMERGENCY': 'Emergency! Call for help immediately.',
      'GOOD_MORNING': 'Good Morning! Have a wonderful day.',
      'GOOD_NIGHT': 'Good Night! Sleep well.',
      'ABUSED': 'Inappropriate gesture! Please maintain respect.',
      'WAIT': 'Wait for me.',
      'POLICE': 'Call the police!',
      'SICK': 'I feel sick.',
      'TIRED': 'I am tired.',
      'SORRY': 'I am sorry.',
      'WORK': 'I am working.',
      'YOU': 'You are a good person.',
      'I': 'I am here.',
      'WAITING': 'Waiting for sign...',
    },
    'ur': {
      'HELP': 'مجھے مدد کی ضرورت ہے! براہ کرم میری مدد کریں۔',
      'HELLO': 'سلام علیکم! آپ کیسے ہیں؟',
      'WATER': 'مجھے پیاس لگی ہے، پانی چاہیے۔',
      'FOOD': 'مجھے بھوک لگی ہے، کھانا دیں۔',
      'DANGER': 'خطرہ! محتاط رہیں اور دور رہیں۔',
      'WASHROOM': 'واش روم / باتھ روم کہاں ہے؟',
      'GOOD': 'بہت اچھا اور عمدہ! شاباش۔',
      'EMERGENCY': 'ہنگامی صورتحال! فوری مدد کیجیے۔',
      'GOOD_MORNING': 'صبح بخیر! آپ کا دن اچھا رہے۔',
      'GOOD_NIGHT': 'شب بخیر! اچھی نیند آئے۔',
      'ABUSED': 'نامناسب اشارہ! براہ کرم احترام رکھیں۔',
      'WAIT': 'میرا انتظار کریں۔',
      'POLICE': 'پولیس کو بلائیں!',
      'SICK': 'میری طبیعت ٹھیک نہیں ہے۔',
      'TIRED': 'میں تھک گیا ہوں۔',
      'SORRY': 'میں معذرت خواہ ہوں۔',
      'WORK': 'میں کام کر رہا ہوں۔',
      'YOU': 'آپ اچھے انسان ہیں۔',
      'I': 'میں یہاں ہوں۔',
      'WAITING': 'اشارے کا انتظار ہے...',
    },
    'sd': {
      'HELP': 'مون کي مدد جي ضرورت آهي! مهرباني ڪري مدد ڪريو.',
      'HELLO': 'سلام عليڪم! توهان ڪيئن آهيو؟',
      'WATER': 'مون کي پياس لڳي آهي، پاڻي کپي.',
      'FOOD': 'مون کي بک لڳي آهي، ماني ڏيو.',
      'DANGER': 'خطرو! هوشيار رهو ۽ پري رهو.',
      'WASHROOM': 'واش روم ڪٿي آهي؟',
      'GOOD': 'تمام سٺو ۽ شاندار! شاباش.',
      'EMERGENCY': 'هنگامي صورتحال! تيزيءَ سان مدد ڪريو.',
      'GOOD_MORNING': 'صبح بخير! توهان جو ڏينهن سٺو گذري.',
      'GOOD_NIGHT': 'شب بخير! مٺي ننڊ ائجي.',
      'ABUSED': 'نا مناسب اشارو! مهرباني ڪري احترام رکو.',
      'WAIT': 'منهنجو انتظار ڪريو.',
      'POLICE': 'پوليس کي گهرايو!',
      'SICK': 'منهنجي طبيعت صحيح ناهي.',
      'TIRED': 'مان ٿڪجي پيو آهيان.',
      'SORRY': 'مان معافي گهران ٿو.',
      'WORK': 'مان ڪم ڪري رهيو آهيان.',
      'YOU': 'توهان سٺا ماڻهو آهيو.',
      'I': 'مان هتي آهيان.',
      'WAITING': 'اشاري جو انتظار آهي...',
    },
    'ar': {
      'HELP': 'أنا بحاجة للمساعدة! ساعدني من فضلك.',
      'HELLO': 'مرحباً! أهلاً بك.',
      'WATER': 'أنا عطشان، أريد ماء.',
      'FOOD': 'أنا جائع، أعطني طعاماً.',
      'DANGER': 'خطر! كن حذراً وابتعد.',
      'WASHROOM': 'أين الحمام؟',
      'GOOD': 'ممتاز وجيد جداً! عمل رائع.',
      'EMERGENCY': 'طوارئ! اطلب المساعدة فوراً.',
      'GOOD_MORNING': 'صباح الخير! أتمنى لك يوماً سعيداً.',
      'GOOD_NIGHT': 'تصبح على خير! نوم هانئ.',
      'ABUSED': 'إشارة غير لائقة! يرجى الالتزام بالاحترام.',
      'WAIT': 'انتظرني من فضلك.',
      'POLICE': 'اتصل بالشرطة!',
      'SICK': 'أنا مريض.',
      'TIRED': 'أنا متعب.',
      'SORRY': 'أنا آسف.',
      'WORK': 'أنا أعمل.',
      'YOU': 'أنت شخص جيد.',
      'I': 'أنا هنا.',
      'WAITING': 'في انتظار الإشارة...',
    }
  };

  static final Map<String, Map<String, String>> wordMap = {
    'en': {
      'HELP': 'Help Sign',
      'HELLO': 'Hello Sign',
      'WATER': 'Water Sign',
      'FOOD': 'Food Sign',
      'DANGER': 'Danger Sign',
      'WASHROOM': 'Washroom Sign',
      'GOOD': 'Good & Excellent Sign',
      'EMERGENCY': 'Emergency Sign',
      'GOOD_MORNING': 'Good Morning Sign',
      'GOOD_NIGHT': 'Good Night Sign',
      'ABUSED': 'Abused Sign',
      'WAIT': 'Wait',
      'POLICE': 'Police',
      'SICK': 'Sick',
      'TIRED': 'Tired',
      'SORRY': 'Sorry',
      'WORK': 'Work',
      'YOU': 'You',
      'I': 'I'
    },
    'ur': {
      'HELP': 'مدد کا اشارہ',
      'HELLO': 'ہیلو کا اشارہ',
      'WATER': 'پانی کا اشارہ',
      'FOOD': 'کھانے کا اشارہ',
      'DANGER': 'خطرہ کا اشارہ',
      'WASHROOM': 'واش روم کا اشارہ',
      'GOOD': 'بہت اچھا کا اشارہ',
      'EMERGENCY': 'ہنگامی صورتحال کا اشارہ',
      'GOOD_MORNING': 'صبح بخیر کا اشارہ',
      'GOOD_NIGHT': 'شب بخیر کا اشارہ',
      'ABUSED': 'نامناسب اشارہ',
      'WAIT': 'انتظار',
      'POLICE': 'پولیس',
      'SICK': 'بیمار',
      'TIRED': 'تھکا',
      'SORRY': 'معذرت',
      'WORK': 'کام',
      'YOU': 'آپ',
      'I': 'میں'
    },
    'sd': {
      'HELP': 'مدد جو اشارو',
      'HELLO': 'هيلو جو اشارو',
      'WATER': 'پاڻي جو اشارو',
      'FOOD': 'ماني جو اشارو',
      'DANGER': 'خطري جو اشارو',
      'WASHROOM': 'واش روم جو اشارو',
      'GOOD': 'تمام سٺو اشارو',
      'EMERGENCY': 'هنگامي صورتحال جو اشارو',
      'GOOD_MORNING': 'صبح بخير جو اشارو',
      'GOOD_NIGHT': 'شب بخير جو اشارو',
      'ABUSED': 'نا مناسب اشارو',
      'WAIT': 'انتظار',
      'POLICE': 'پوليس',
      'SICK': 'بيمار',
      'TIRED': 'ٿڪل',
      'SORRY': 'معافي',
      'WORK': 'ڪم',
      'YOU': 'توهان',
      'I': 'مان'
    },
    'ar': {
      'HELP': 'إشارة المساعدة',
      'HELLO': 'إشارة الترحيب',
      'WATER': 'إشارة الماء',
      'FOOD': 'إشارة الطعام',
      'DANGER': 'إشارة الخطر',
      'WASHROOM': 'إشارة الحمام',
      'GOOD': 'إشارة الجودة والامتياز',
      'EMERGENCY': 'إشارة الطوارئ',
      'GOOD_MORNING': 'إشارة صباح الخير',
      'GOOD_NIGHT': 'إشارة تصبح على خير',
      'ABUSED': 'إشارة تحذيرية',
      'WAIT': 'انتظر',
      'POLICE': 'شرطة',
      'SICK': 'مريض',
      'TIRED': 'متعب',
      'SORRY': 'آسف',
      'WORK': 'عمل',
      'YOU': 'أنت',
      'I': 'أنا'
    }
  };

  static String get(String key) {
    return _strings[currentLanguage]?[key] ?? _strings['en']?[key] ?? key;
  }

  static String getSignPhrase(String sign) {
    return multiLangMap[currentLanguage]?[sign] ?? multiLangMap['en']?[sign] ?? sign;
  }

  static String getSignWord(String sign) {
    return wordMap[currentLanguage]?[sign] ?? wordMap['en']?[sign] ?? sign;
  }

  static TextDirection get textDirection {
    return ['ur', 'sd', 'ar'].contains(currentLanguage)
        ? TextDirection.rtl
        : TextDirection.ltr;
  }
}
